# Generated by Django 4.2.10 on 2024-03-17 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.RemoveField(
            model_name='myfile',
            name='title',
        ),
        migrations.AddField(
            model_name='myfile',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
