# Generated by Django 4.2.10 on 2024-03-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0003_myfile_description_myfile_title_alter_myfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='description',
            field=models.TextField(),
        ),
    ]
