# Generated by Django 5.0.2 on 2024-03-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0005_myfile_admin_notes_myfile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='New', max_length=22),
        ),
    ]
