# Generated by Django 4.2.10 on 2024-03-30 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0005_myfile_user'),
        ('oauth_app', '0006_alter_myfile_status'),
    ]

    operations = [
    ]
