# Generated by Django 4.2.10 on 2024-03-31 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0007_merge_0005_myfile_user_0006_alter_myfile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfile',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='myfile',
            name='status',
        ),
    ]
