# Generated by Django 4.2.10 on 2024-03-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0008_remove_myfile_admin_notes_remove_myfile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfile',
            name='isNew',
            field=models.BooleanField(default=True),
        ),
    ]
