# Generated by Django 4.2.10 on 2024-04-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0010_remove_myfile_isnew_myfile_admin_notes_myfile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
